version: "3"
services:
  database:
    image: mariadb:latest
    container_name: hillel-db
    restart: always
    ports:
      - "127.0.0.1:33061:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=123456789
      - MARIADB_DATABASE=hillel
    volumes:
      - ./db-data:/var/lib/mysql

  web:
    image: nginx:1.21-alpine
    container_name: hillel-web
    restart: always
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../..:/var/www/app
    restart: always
    depends_on:
      - database

#  php-fpm
#  nginx
#  mariadb +